services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROK_API_KEY=xai-eVoa0lqPpkKXTrLHkahf3g5BYD6uWEOvaZGhSdz5mJxxxTrgOHYmYNefGdoWVDKYPVDwbyzBzmNy5vl8
      - GROK_MODEL=grok-2-latest
      - WHISPER_CPP_PATH=/app/whisper.cpp/build/bin/whisper-cli
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - whisper_models:/app/whisper_models
    restart: unless-stopped

volumes:
  whisper_models: